# Generated by Django 3.2.6 on 2021-08-31 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AulaAvulsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('horainicio', models.TimeField()),
                ('horafim', models.TimeField()),
                ('motivo', models.TextField()),
                ('observacao', models.TextField(blank=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocorrencia.curso')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocorrencia.filial')),
            ],
        ),
    ]
