# Generated by Django 3.2.6 on 2021-08-31 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('horafim', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='aulaavulsa',
            name='horafim',
        ),
        migrations.RemoveField(
            model_name='aulaavulsa',
            name='motivo',
        ),
        migrations.AddField(
            model_name='aulaavulsa',
            name='hora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ocorrencia.hora'),
            preserve_default=False,
        ),
    ]
