# Generated by Django 3.2.6 on 2021-08-31 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0002_auto_20210831_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hora',
            old_name='horafim',
            new_name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='aulaavulsa',
            name='horainicio',
        ),
    ]
