# Generated by Django 3.2.6 on 2021-08-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0003_auto_20210831_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulaavulsa',
            name='motivo',
            field=models.TextField(blank=True),
        ),
    ]
