# Generated by Django 3.2.6 on 2021-08-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0004_aulaavulsa_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulaavulsa',
            name='motivo',
            field=models.TextField(),
        ),
    ]
